Jsonrpc to Jsonrpsee Migration
ava-labs/avalanche-rs pull request #88
Opened 2023-11-09 12:22 UTC by Angel-Petrov

Fixes #39

This replaces both `jsonrpc-core` and `jsonrpc-http-server` with the newer `jsonrpsee-core` and `jsonrpsee-types` crates. The new jsonrpsee crates have been moved into `dev-dependencies` as jsonrpc was only used for its re-exported `futures` module in the `avalanche-types` library (which was able to be replaced).

The majority of this PR has been modifying tests in `crates/avalanche-types/tests/rpc/` as that was the primary use of jsonrpc.

2023-11-09 16:46 UTC, richardpringle requested changes
Haha 😅  so this was a fun exercise... 

Turns out we don't need to migrate to `jsonrpsee`, but remove the dependency entirely. We had a single test, testing code that was written inside the integration tests directory... so silly. 

Anyway, I think my change requests are pretty clear. Let me know if you have any questions and thank you for the contribution!

2023-11-09 16:46 UTC, richardpringle commented on crates/avalanche-types/src/subnet/rpc/utils/grpc.rs
👍

2023-11-09 16:46 UTC, richardpringle commented on crates/avalanche-types/tests/rpc/common.rs
> +        params: Some(&*raw_params),
another nit: 
```suggestion
        params: Some(&raw_params),
```

2023-11-09 16:46 UTC, richardpringle commented on crates/avalanche-types/tests/rpc/common.rs
> +        method: Cow::Borrowed(method_name).into(),
nit:
```suggestion
        method: method_name.into(),
```

2023-11-09 16:46 UTC, richardpringle commented on crates/avalanche-types/tests/rpc/common.rs
🤔 

This is all a little useless... sorry that you went through the work, but I realized that at the end of the file, none of this stuff is actually being used. 

Can you delete everything in this file with the exception of the `serve_test_database` function (and the necessary imports of course).

Happy to PR myself if you prefer since it's outside of the scope of what you were actually trying to accomplish, though.

2023-11-09 16:46 UTC, richardpringle commented on crates/avalanche-types/tests/rpc/common.rs
> +        params: Some(&*raw_params),
Ignore this

2023-11-09 16:48 UTC, richardpringle commented on crates/avalanche-types/tests/rpc/common.rs
> +        method: Cow::Borrowed(method_name).into(),
Ignore this too... but just FYI, no need to convert from `&str` to `std::borrow::Cow` and then to `beef::Cow`. I'm sure the assembly would have been the same, but 🤷

2023-11-10 08:32 UTC, Angel-Petrov commented on crates/avalanche-types/tests/rpc/common.rs
Does this also include `test_http_service` in `mod.rs`? Since that also uses these methods.

2023-11-13 15:24 UTC, richardpringle commented on crates/avalanche-types/tests/rpc/common.rs
Hey @Angel-Petrov, sorry for the delayed response. Yes, this includes `test_http_service` in `mod.rs`. And I think you're right, moving `serve_test_database` to `mod.rs` would be better too.

2023-11-13 17:48 UTC, richardpringle approved these changes
Gotta love the number of deletions here. If CI passes, we can merge!

2023-11-14 04:04 UTC, gyuho approved these changes
lgtm, awesome

2023-11-14 13:22 UTC, merged